x-ros2-common: &ros2-common
  build:
    context: .
    dockerfile: Dockerfile
  image: arc380_ros2:latest
  network_mode: host

  volumes:
    - ../workshops:/workshops
    - ../scripts:/scripts
    - ../realsense_shared:/realsense_shared

  environment:
    - DISPLAY=:1
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - CYCLONEDDS_URI=/cyclonedds.xml
    - LIBGL_ALWAYS_SOFTWARE=1
    - GALLIUM_DRIVER=llvmpipe
    - QT_X11_NO_MITSHM=1

  ipc: host
  stdin_open: true
  tty: true
  restart: unless-stopped

services:
  ros2_sim:
    <<: *ros2-common
    container_name: arc380_ros2
    # no command override, so entrypoint.sh runs simulation by default

  ros2_real:
    <<: *ros2-common
    container_name: arc380_ros2_real
    command: ros2 launch abb_egm_controller egm_controller.launch.py
