x-ros2-common: &ros2-common
  build:
    context: .
    dockerfile: Dockerfile
  image: arc380_ros2:latest

  volumes:
    - ../workshops:/ros2_ws/workshops
    - ../scripts:/ros2_ws/scripts
    - ../realsense_shared:/ros2_ws/realsense_shared
    - ../training_data:/ros2_ws/training_data
    - ../workshops:/workshops
    - ../scripts:/scripts
    - ../src:/ros2_ws/src

  environment:
    - DISPLAY=:1
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - CYCLONEDDS_URI=/cyclonedds.xml
    - LIBGL_ALWAYS_SOFTWARE=1
    - GALLIUM_DRIVER=llvmpipe
    - QT_X11_NO_MITSHM=1

  ipc: host
  stdin_open: true
  tty: true
  restart: unless-stopped

services:
  ros2_sim:
    <<: *ros2-common
    container_name: arc380_ros2
    ports:
      - "6080:6080"
    environment:
      - SIM_WORLD_FILE=validation_workcell.sdf
    volumes:
      - ../workshops:/ros2_ws/workshops
      - ../scripts:/ros2_ws/scripts
      - ../realsense_shared:/ros2_ws/realsense_shared
      - ../training_data:/ros2_ws/training_data
      - ../workshops:/workshops
      - ../scripts:/scripts
      - ../src:/ros2_ws/src
      - ../src/abb_irb120_gazebo/launch/gz_moveit.launch.py:/ros2_ws/install/abb_irb120_gazebo/share/abb_irb120_gazebo/launch/gz_moveit.launch.py
      - ../src/abb_irb120_gazebo/worlds/validation_workcell.sdf:/ros2_ws/install/abb_irb120_gazebo/share/abb_irb120_gazebo/worlds/validation_workcell.sdf
    # no command override, so entrypoint.sh runs simulation by default

  ros2_real:
    <<: *ros2-common
    container_name: arc380_ros2_real
    ports:
      - "6511:6511/udp"
    command: ros2 launch abb_egm_controller egm_controller.launch.py
